from bitcoin import *
outfile = open('wallet.txt','w')
private_key =random_key()
print (private_key)
public_key = privtopub (private_key)
print (public_key)
address = pubtoaddr (public_key)
print ('my address is :' +address)
outfile.write ('my bitcoin address :' +address+ '\n')
outfile.write ('my public key :' +privtopub (private_key)+ '\n')
outfile.write ('my hexadecimal private key :' +private_key +'/n')
pub1 = privtopub(random_key())
pub2 = privtopub(random_key())
pub3 = privtopub(random_key())
multi = mk_multisig_script (pub1, pub2, pub3, 2, 3)
maddr = scriptaddr (multi)
print (maddr)
